services:
  sk-presentation:
    image: ghcr.io/netwatwezoeken/semantic-kernel-presentation
    restart: unless-stopped
    labels:
      - traefik.http.routers.sk.rule=Host(`sk.netwatwezoeken.nl`)
      - traefik.http.routers.sk.tls=true
      - traefik.docker.network=proxy
#      - traefik.http.routers.sk.middlewares=auth
#      - traefik.http.middlewares.auth.basicauth.users=${SECRET}
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true
