<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>642e4c3a-e0be-472e-be39-e523eb2cb98b</UserSecretsId>
        <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.2" />
        <PackageReference Include="Aspire.Hosting.Redis" Version="9.5.2" />
        <PackageReference Include="CommunityToolkit.Aspire.Hosting.Ollama" Version="9.8.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\05b-MCPServer\05b-MCPServer.csproj" />
      <ProjectReference Include="..\07-Rag\07-Rag.csproj" />
      <ProjectReference Include="..\WebUI\WebUI\WebUI.csproj" />
    </ItemGroup>

</Project>
