services:
  redis:
    image: redis/redis-stack-server
    volumes:
      - ./config:/usr/local/etc/redis:rw
      - ./config/redis-stack.conf:/redis-stack.conf
      - ./data:/data
    ports:
      - '6379:6379'
    restart: unless-stopped